### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by porst17**
This PR is meant for handling the French translation by @danielramosg.

### CODE REVIEW

**Comment by elondaits** [comment]
@danielramosg @porst17 
There are two images that also need translation:

- [Fig 1](https://github.com/IMAGINARY/neural-numbers/blob/master/assets/img/what-is-a-neural-network-fig-1.svg)
- [Fig 2](https://github.com/IMAGINARY/neural-numbers/blob/master/assets/img/what-is-a-neural-network-fig-2.svg)

The source for those translations is [this Illustrator file](https://github.com/IMAGINARY/neural-numbers/blob/master/src/art/graphics.ai). I can quickly take care of them if you give me the text I should use (it can be through a comment here).

Ideally don't edit the SVG directly because the texts were converted to strokes, and it would be good to use the same font.

**Comment by porst17** [comment]
@elondaits Do you mind managing this PR (reviewing, merging and releasing a new version)? I haven't worked on Neural Numbers much, so I think it would be better if someone could check and integrate the translation who is really into it. I would assign you to the PR then. Thank you.

**Comment by danielramosg** [comment]
@elondaits Those are the translated words for the two figures:
```
Fig 1

Input layer           Couche d'entrée
Hidden layer(s)       Couche(s) cachée(s)
Output layer          Couche de sortie
Input X               Entrée X
Output                Sortie


Fig 2

Input                 Valeurs d'entrée
Weights               Poids
Summation             Somme
Bias                  Biais
Activation function   Fonction d'activation
Output                Valeur de sortie  

```

**Comment by danielramosg** [comment]
All the texts in French are ready. A couple of caveats:
- The layout should be revised since many texts (e.g. button labels) are longer in French than in English.
- In the font used for titles (Gap Sans Bold), the apostrophe (') is a bit too low; if possible I would raise it to cap height. Other French characters like Ç are not available in this font (in bold), but luckily we don't have any in this app.

**Pull request merged**
